project:
  type: website

website:
  sidebar:
    style: docked
    title: "Stat 999"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-scf/course-site-quarto
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: calendar.qmd
        text: Calendar
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.ipynb
          - units/unit3.qmd
      - href: data.qmd
        text: Datasets
    footer: 
      <a href="license.qmd">License</a>
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



